spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # ?? PostgreSQL ?? (?? 5432)
    url: jdbc:postgresql://localhost:5432/resume_db
    # ?? ?? ??? ??? 'postgres' / 'password'? ????? ??
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    # Entity ???? ???? ?????? ???? ?? ??/?? (?? ???)
    hibernate:
      ddl-auto: update
    # JPA? ???? SQL ??? ???? ??? ????? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100